export const CLOSE_WEBVIEW = 'CLOSE_WEBVIEW'
export const INIT_USER = 'INIT_USER'
export const INIT_USER_SUCCESS = 'INIT_USER_SUCCESS'
export const INIT_USER_FAILURE = 'INIT_USER_FAILURE'

export const SCHEDULE_SESSION = 'SCHEDULE_SESSION'
export const SCHEDULE_SESSION_SUCCESS = 'SCHEDULE_SESSION_SUCCESS'
export const SCHEDULE_SESSION_FAILURE = 'SCHEDULE_SESSION_FAILURE'
