export const CLOSE_WEBVIEW = 'CLOSE_WEBVIEW'
// export const POST_FORM_FIELD = 'POST_FORM_FIELD'
export const INIT_USER = 'INIT_USER'

export const HELP_1_0 = 'HELP_1_0'

export const UPDATE_FORM = 'UPDATE_FORM'
export const UPDATE_FORM_SUCCESS = 'UPDATE_FORM_SUCCESS'
export const UPDATE_FORM_FAILURE = 'UPDATE_FORM_FAILURE'

export const GET_FORM = 'GET_FORM'
export const GET_FORM_SUCCESS = 'GET_FORM_SUCCESS'
export const GET_FORM_FAILURE = 'GET_FORM_FAILURE'

export const COMPLETE_FORM = 'COMPLETE_FORM'
export const COMPLETE_FORM_SUCCESS = 'COMPLETE_FORM_SUCCESS'
export const COMPLETE_FORM_FAILURE = 'COMPLETE_FORM_FAILURE'

export const SEND_POSTBACK_EVENT = 'SEND_POSTBACK_EVENT'
