export const CLOSE_WEBVIEW = 'CLOSE_WEBVIEW'
export const INIT_USER = 'INIT_USER'
export const INIT_USER_SUCCESS = 'INIT_USER_SUCCESS'
export const INIT_USER_FAILURE = 'INIT_USER_FAILURE'

export const SCHEDULE_SESSION = 'SCHEDULE_SESSION'
export const SCHEDULE_SESSION_SUCCESS = 'SCHEDULE_SESSION_SUCCESS'
export const SCHEDULE_SESSION_FAILURE = 'SCHEDULE_SESSION_FAILURE'

export const SCHEDULE_TIMEPERIOD = 'SCHEDULE_TIMEPERIOD'
export const SCHEDULE_TIMEPERIOD_SUCCESS = 'SCHEDULE_TIMEPERIOD_SUCCESS'
export const SCHEDULE_TIMEPERIOD_FAILURE = 'SCHEDULE_TIMEPERIOD_FAILURE'

export const REMOVE_TIMEPERIOD = 'REMOVE_TIMEPERIOD'
export const REMOVE_TIMEPERIOD_SUCCESS = 'REMOVE_TIMEPERIOD_SUCCESS'
export const REMOVE_TIMEPERIOD_FAILURE = 'REMOVE_TIMEPERIOD_FAILURE'
